### ISSUE TITLE
https://blog.coolaj86.com get ssl error on chrome

### ISSUE THREAD

**Issue by mehdishahdoost** [coolaj86/nodejs-ssl-example#5]
![ssl-error](https://cloud.githubusercontent.com/assets/251942/11019116/c2af487a-85fe-11e5-9514-8e5f1487c3bd.jpg)

this link https://blog.coolaj86.com/articles/how-to-create-a-csr-for-https-tls-ssl-rsa-pems/ get ssl error
on chrome.

**Comment by coolaj86** [comment]
Thanks!

The cause of the problem is that I updated my webserver to prioritize upgrading to https before handling redirects. I don't have a certificate for blog.coolaj86.com (so it uses a dummy as the default) and it redirects to coolaj86.com.

I've updated the links for now and I'll get a proper certificate for blog.coolaj86.com as soon as letsencrypt launches. At that time I'll also be switching over to [caddy](https://caddyserver.com) as my webserver.
